# config/packages/security.yaml
security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\InMemoryUser: bcrypt

    providers:
        in_memory: { memory: ~ }
        users:
            entity:
                class: 'App\Entity\User'
                property: 'username'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: users
            form_login:
                login_path: login
                check_path: login_check
                always_use_default_target_path:  true
                default_target_path:  /
            entry_point: form_login
            logout: ~

            login_throttling:
                max_attempts: 3
                interval: '15 minutes'

    access_control:
        - { path: ^/login,  roles: PUBLIC_ACCESS }
        - { path: ^/users/create, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER